<script setup lang="ts">
  import { PageWrapper } from '/@/components/Page';
  import { BasicTitle } from '/@/components/Basic';
  import { Card, Col, Divider } from 'ant-design-vue';
  import { BasicForm, useForm } from '/@/components/Form';
  import { ref } from 'vue';
  import Chart from './Chart.vue';
  import Table from './Table.vue';

  const help = `
  Life cycle value (LTV) is a summary indicator used to track the revenue generated by a group (a group of Contacts grouped by registration period) over a period of time (revenue includes the number of subscription and purchase additional messages sent)
  `;

  const currentKey = ref('chart');

  const [registerForm] = useForm({
    schemas: [
      {
        label: '',
        field: '1',
        component: 'Select',
        componentProps: {
          placeholder: 'View by month',
        },
        colProps: {
          flex: '300px',
        },
      },
      {
        label: '',
        field: '2',
        component: 'Select',
        componentProps: {
          placeholder: 'From the first month',
        },
        colProps: {
          flex: '300px',
        },
      },
      {
        label: '',
        field: '3',
        component: 'Select',
        componentProps: {
          placeholder: 'Until the last full month',
        },
        colProps: {
          flex: '300px',
        },
      },
    ],
    showAdvancedButton: false,
    showActionButtonGroup: false,
    rowProps: {
      gutter: 30,
    },
  });
</script>

<template>
  <PageWrapper content-full-height dense content-class="bg-[#fff]">
    <Card :bordered="false">
      <BasicTitle :help-message="help" class="mb-5">Life time value(LTV) Analysis </BasicTitle>

      <BasicForm @register="registerForm">
        <template #formHeader>
          <Col :order="9" flex="auto">
            <div class="text-right text-base">
              <span
                class="hover:text-blue-400 cursor-pointer"
                :class="{ 'text-blue-400': currentKey === 'chart' }"
                @click="currentKey = 'chart'"
              >
                Chart
              </span>
              <Divider type="vertical" />
              <span
                class="hover:text-blue-400 cursor-pointer"
                :class="{ 'text-blue-400': currentKey === 'sheet' }"
                @click="currentKey = 'sheet'"
              >
                Sheet
              </span>
            </div>
          </Col>
        </template>
      </BasicForm>

      <template v-if="currentKey === 'chart'">
        <Chart />
      </template>
      <template v-else>
        <Table />
      </template>
    </Card>
  </PageWrapper>
</template>
